services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    working_dir: /var/www/html
    volumes:
      - ./hotels:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: hotels
      DB_USERNAME: postgres
      DB_PASSWORD: 456
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    image: node:18.20.6
    working_dir: /app
    volumes:
      - ./front:/app
    command: >
      sh -c "
        npm install &&
        npm run build &&
        npx serve -s dist -l 3000
      "
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  